project_id = "nbbdjtqhlkkfqdhkzrnf"

[functions.generate-insights]
verify_jwt = false

[functions.generate-template]
verify_jwt = false

[api]
enabled = true
port = 54321
max_rows = 1000

[api.schemas]
enabled = ["public", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[auth]
enabled = true
port = 54324
site_url = "http://127.0.0.1:3000"
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
max_frequency = "1h"
secure_password_change = false
template_confirmation = ""
template_invite = ""
template_magic_link = ""
template_recovery = ""

[auth.sms]
enable_signup = false
enable_confirmations = false
max_frequency = "1h"
template_confirmation = ""
template_invite = ""
template_magic_link = ""
template_recovery = ""

[edge_runtime]
enabled = true
port = 54325
inspector_port = 8083

[edge_runtime.policy]
[edge_runtime.policy.resources]
[edge_runtime.policy.resources.limits]
memory_mb = 150
timeout_ms = 10000
[edge_runtime.policy.resources.reserved]
memory_mb = 10

[analytics]
enabled = true
port = 54327
vector_port = 54328
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcp.json"

[inbucket]
enabled = true
port = 54326
smtp_port = 54325
pop3_port = 54327
